require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - Gemfile
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/**/*
    - app/mailers/application_mailer.rb
    - config.ru
    - db/**/*

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Rakefile
    - test/test_helper.rb
    - config/**/*
    - app/mailers/application_mailer.rb
    - config.ru
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 15

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
    - config/**/*

Style/PercentLiteralDelimiters:
  Exclude:
    - Gemfile
    - config/**/*

Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb

Style/BlockComments:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Layout/ArgumentAlignment:
  Exclude:
    - config/**/*

Layout/MultilineMethodCallIndentation:
  Exclude:
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/RedundantConstantBase:
  Exclude:
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

RSpec/HookArgument:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/RedundantFetchBlock:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
